config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :prayer
  validates :date, presence: true
end

app/models/day.rb
class Day < ApplicationRecord
    has_many :prayers, dependent: :destroy
end

app/models/prayer.rb
class Prayer < ApplicationRecord
  belongs_to :day
  belongs_to :room
  has_many :bookings

  def capacity_prayer_reset
    yesterday = Date.today - 1
    yesterday_name = yesterday.strftime("%A")
    prayers_yesterday_homme = Prayer.all.where(room_id: Room.all.find_by_name('Homme'), day_id: Day.all.find_by_name(yesterday_name))
    prayers_yesterday_femme = Prayer.all.where(room_id: Room.all.find_by_name('Femme'), day_id: Day.all.find_by_name(yesterday_name))

    prayers_yesterday_homme.each do |prayer|
      prayer.capacity_prayer = Room.all.find_by_name('Homme').capacity_room
    end

    prayers_yesterday_femme.each do |prayer|
      prayer.capacity_prayer = Room.all.find_by_name('Femme').capacity_room
    end
  end

end

app/models/room.rb
class Room < ApplicationRecord
    has_many :prayers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_many :bookings

    validates :first_name, :last_name, :email, :phone_number,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
require 'date'

class BookingsController < ApplicationController
  
  def index
    @bookings = Booking.all
  end
  
  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new
    prayers_ids = params[:booking][:prayers]
    prayers_ids.each do |_key, value|
      if !value.empty? 
        @prayer_id = value.to_i
      end
    end
    prayer = Prayer.find(@prayer_id)
    @booking.prayer = prayer
    @booking.date = Date.today
    new_user = params[:booking][:users]
    user = User.new(first_name: new_user[:first_name], last_name: new_user[:last_name], email: new_user[:email], phone_number: new_user[:phone_number])
    if !(@booking.prayer.capacity_prayer < 1) && user.save
      @booking.user = user
      if @booking.save
        @booking.prayer.capacity_prayer -= 1
        @booking.prayer.save
        redirect_to booking_path(@booking)
      else
        render "new", alert: "HELLOO"
      end
    else
      render "new", alert: "HELLOO 22222"
    end
  end


  def capacity_prayer_reset
    yesterday = Date.today - 1
    yesterday_name = yesterday.strftime("%A")
    prayers_yesterday_homme = Prayer.all.where(room_id: Room.all.find_by_name('Homme'), day_id: Day.all.find_by_name(yesterday_name))
    prayers_yesterday_femme = Prayer.all.where(room_id: Room.all.find_by_name('Femme'), day_id: Day.all.find_by_name(yesterday_name))

    prayers_yesterday_homme.each do |prayer|
      prayer.capacity_prayer = Room.all.find_by_name('Homme').capacity_room
    end

    prayers_yesterday_femme.each do |prayer|
      prayer.capacity_prayer = Room.all.find_by_name('Femme').capacity_room
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @days = Day.all
    @rooms = Room.all
    @prayers = Prayer.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<h1>Réservations des prières </h1>

<% @bookings.each do |booking| %>
    <div>
        <p>----------------------------------------------------------</p>
        <p>----------------------------------------------------------</p>
        <h4>Informations personnelles :</h4>
        <p>Prénom : <%= booking.user.first_name %></p>
        <p>Nom : <%= booking.user.last_name %></p>
        <p>Email : <%= booking.user.email %></p>
        <p>Téléphone : <%= booking.user.phone_number %></p>
        <h4>Informations sur la prière :</h4>
        <p>Nom de la prière : <%= booking.prayer.name %></p>
        <p>Salle de la prière : <%= booking.prayer.room.name %></p>
        <p>Places restantes : <%= booking.prayer.capacity_prayer %></p>
        <p>Jour de la prière : <%= booking.prayer.day.name %></p>
        <p>Date de la réservation : <%= booking.date %></p>
    </div>
<% end %>

app/views/bookings/new.html.erb
<div class="text-container">
  <h1>ACMBOOKING</h1>
  <h2>RÉSERVER VOTRE PLACE DE PRIÈRE</h2>
  <h4>La mosquée est ouverte</h4>
  <a href="https://www.mawaqit.net/fr/mosquee-de-bonneville" target="_blank">Consulter les horaires de prières</a>
</div>

<br>

<div class="prayer-container">  

  <div class="bloc-today">
    <%= Time.now.strftime("%A %d %B %Y") %><br>
    <button id="button-homme-today" class="btn btn-primary btn-lg">HOMME</button>
    <button id="button-femme-today" class="btn btn-primary btn-lg">FEMME</button>
  </div>

  <br>

  <div class="bloc-tomorrow">
    <% tomorrow = Date.today + 1 %>
    <%= tomorrow.strftime("%A %d %B %Y") %><br>
    <button id="button-homme-tomorrow" class="btn btn-primary btn-lg">HOMME</button>
    <button id="button-femme-tomorrow" class="btn btn-primary btn-lg">FEMME</button>
  </div>

</div>

<div class="prayer-select">
  <%= simple_form_for(@booking) do |f| %>

    <div class="prayer-homme-today" hidden>
      <%= f.fields_for :prayers do |fff| %>
        <%= fff.input :prayers_homme_today, as: :radio_buttons, collection: Day.where(name: Date.today.strftime("%A")).first.prayers.where(room_id: Room.all.first) %>
      <% end %>
    </div>

    <div class="prayer-femme-today" hidden>
      <%= f.fields_for :prayers do |fff| %>
        <%= fff.input :prayers_femme_today, as: :radio_buttons, collection: Day.where(name: Date.today.strftime("%A")).first.prayers.where(room_id: Room.all.last) %>
      <% end %>
    </div>

    <div class="prayer-homme-tomorrow" hidden>
      <%= f.fields_for :prayers do |fff| %>
        <% tomorrow = Date.today + 1 %>
        <%= fff.input :prayers_homme_tomorrow, as: :radio_buttons, collection: Day.where(name: tomorrow.strftime("%A")).first.prayers.where(room_id: Room.all.first) %>
      <% end %>
    </div>

    <div class="prayer-femme-tomorrow" hidden>
      <%= f.fields_for :prayers do |fff| %>
        <% tomorrow = Date.today + 1 %>
        <%= fff.input :prayers_femme_tomorrow, as: :radio_buttons, collection: Day.where(name: tomorrow.strftime("%A")).first.prayers.where(room_id: Room.all.last) %>
      <% end %>
    </div>

    <%= f.fields_for :users do |ff| %>
      <%= ff.input :first_name %>
      <%= ff.input :last_name %>
      <%= ff.input :email %>
      <%= ff.input :phone_number %>
    <% end %>

    <div class="button-submit" hidden><%= f.submit value: "Réserver votre prière" %> </div>
    
  <% end %>
</div>

<script src="../../javascript/packs/application.js"></script>

app/views/bookings/show.html.erb
<h1>Récapitulatif de votre réservation de prière <%= @booking.user.first_name %></h1>

<div>
    <p>----------------------------------------------------------</p>
    <h3>Informations personnelles :</h3>
    <p>Prénom : <%= @booking.user.first_name %></p>
    <p>Nom : <%= @booking.user.last_name %></p>
    <p>Email : <%= @booking.user.email %></p>
    <p>Téléphone : <%= @booking.user.phone_number %></p>
    <h3>Informations sur la prière :</h3>
    <p>Nom de la prière : <%= @booking.prayer.name %></p>
    <p>Salle de la prière : <%= @booking.prayer.room.name %></p>
    <p>Places restantes : <%= @booking.prayer.capacity_prayer %></p>
    <p>Jour de la prière : <%= @booking.prayer.day.name %></p>
    <p>Date de la réservation : <%= @booking.date %></p>
</div>

<%= link_to "Nouvelle résérvation de prière", new_booking_path, class: "btn-flat" %>


    <%# <p>Prénom : <%= @booking.user[:first_name] %'></p>
    <p>Nom : <%= @booking.user[:last_name] %'></p>
    <p>Email : <%= @booking.user[:email] %'></p>
    <p>Téléphone : <%= @booking.user[:phone_number] %'></p>
    <p>Genre : <%= @booking.user[:genre] %'></p> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acmbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

<h2>Affichage des seeds du model Day :</h2>

<% @days.each do |day| %>
        <p>Nom du jour : <%= day.name %></p>
<% end %>

<p>----------------------------------------------------------------------</p>

<h2>Affichage des seeds du model Room :</h2>

<% @rooms.each do |room| %>
        <p>Nom de la salle : <%= room.name %></p>
        <p>Capacité de la salle : <%= room.capacity_room %></p>
<% end %>

<p>----------------------------------------------------------------------</p>

<h2>Affichage des seeds du model Prayers :</h2>

<% @prayers.each do |prayer| %>
        <p>Nom de la prière : <%= prayer.name %></p>
        <p>Capacité de la prière : <%= prayer.capacity_prayer %></p>
        <p>Jour de la prière : <%= prayer.day.name%></p>
        <p>Salle de la prière : <%= prayer.room.name %></p>

<p>----------------------------------------</p>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>